version: '3.8'

services:

  app:
    image: backend-image
    build: ./backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      FRONTEND_URL: ${FRONTEND_URL}
    networks:
      - my-shared-network



  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public
      - ./frontend/package.json:/usr/src/app/package.json
    ports:
      - "${REACT_APP_FRONTEND_PORT}:3000" 
    environment:
      CHOKIDAR_USEPOLLING: true
      REACT_APP_BACKEND_URL: ${REACT_APP_BACKEND_URL}
    depends_on:
      - app



networks:
  my-shared-network:
    external: true