version: '3.8'

services:

  app:
    image: backend-image
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle-db:1521/XEPDB1
      SPRING_DATASOURCE_USERNAME: system
      SPRING_DATASOURCE_PASSWORD: password
      FRONTEND_URL: http://localhost:3000
    networks:
      - my-shared-network



  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public
      - ./frontend/package.json:/usr/src/app/package.json
    ports:
      - "3000:3000" 
    environment:
      CHOKIDAR_USEPOLLING: true
      REACT_APP_BACKEND_URL: http://localhost:8080
    depends_on:
      - app



networks:
  my-shared-network:
    external: true